SpiritMarket/Models/Shop.cs
using System.ComponentModel.DataAnnotations;
using System;
using System.Collections.Generic;

namespace SpiritMarket.Models{
    public class Shop{
        [Key]
        public int ShopId {get; set;}

        [Required(ErrorMessage="What's the name of your store?")]
        [MaxLength(32, ErrorMessage="Hey, we wanted a shop name, not your whole life story... could you shorten that to 32 characters?")]
        public string Name {get; set;}

        public int UserId {get; set;}
        public User User {get; set;}

        public List<ListedItem> Items {get; set;}


        public DateTime Created_At{get; set;}
        public DateTime Updated_At{get; set;}

        public Shop(){
            Items = new List<ListedItem>();
            Created_At = DateTime.Now;
            Updated_At = DateTime.Now;
        }
    }
}

SpiritMarket/Areas/Gameplay/Controllers/ShopsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SpiritMarket.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;

namespace SpiritMarket.Areas.Gameplay
{
    [Route("shops")]
    public class ShopsController : GameplayController
    {
        public ShopsController(SpiritContext c) : base(c) { }

        [HttpGet]
        [Route("")]
        [Route("all")]
        public IActionResult AllShops(){
            ViewBag.User = context.GetOneUser(HttpContext.Session.GetInt32("UserId"));
            if(ViewBag.User == null){
                return RedirectToAction("Index", "Home", new {area = "Account"});
            }
            ViewBag.AllShops = context.Shops.Include(shop => shop.User).
                                Where(shop => shop.UserId != HttpContext.Session.GetInt32("UserId")).ToList();
            return View("AllShops");
        }

        [HttpGet]
        [Route("me")]
        public IActionResult MyShop(){
            ViewBag.User = context.GetOneUser(HttpContext.Session.GetInt32("UserId"));
            if(ViewBag.User == null){
                return RedirectToAction("Index", "Home", new {area = "Account"});
            }
            ViewBag.ErrorMessage = TempData["ErrorMessage"];
            ViewBag.MyShop = context.Shops.Include(shop => shop.Items).ThenInclude(listed => listed.Item).
            SingleOrDefault(shop => shop.UserId == HttpContext.Session.GetInt32("UserId"));
            ViewBag.NoMoney = TempData["NoMoney"];
            if(ViewBag.MyShop == null){
                return View("CreateMyShop");
            }
            return View("MyShop");
        }

        [HttpPost]
        [Route("create")]
        public IActionResult CreateShop(Shop shop){
            ViewBag.User = context.GetOneUser(HttpContext.Session.GetInt32("UserId"));
            if(ViewBag.User == null){
                return RedirectToAction("Index", "Home", new {area = "Account"});
            }
            if(ModelState.IsValid){
                User CurUser = context.GetOneUser(HttpContext.Session.GetInt32("UserId"));
                if(CurUser.SubtractMoney(75)){
                    shop.UserId = CurUser.UserId;
                    context.Add(shop);
                    context.SaveChanges(); 
                }
                else{
                    TempData["NoMoney"] = "Hey! I said shops were easy to set up, not free! Come back once you have 75 SG!";
                }
                return RedirectToAction("MyShop");
            }
            else{
                return View("CreateMyShop");
            }
        }

        [HttpGet]
        [Route("{username}")]
        public IActionResult OtherShop(string username){
            //if my id, redirect to shops/me
            ViewBag.User = context.GetOneUser(HttpContext.Session.GetInt32("UserId"));
            if(ViewBag.User == null){
                return RedirectToAction("Index", "Home", new {area = "Account"});
            }
            ViewBag.OtherUser = context.GetOneUser(username);
            int OtherUserId = ViewBag.OtherUser.UserId;
            if(ViewBag.OtherUser == null){
                return RedirectToAction("Index", "Home", new {area = "Account"});
            }

            ViewBag.Shop = context.Shops.Include(shop => shop.Items).ThenInclude(listed => listed.Item).
            SingleOrDefault(shop => shop.UserId == OtherUserId);
            if(ViewBag.Shop == null || ViewBag.Shop.UserId == ViewBag.User.UserId){
                return RedirectToAction("MyShop");
            }

            ViewBag.Success = TempData["Success"];
            ViewBag.Error = TempData["Error"];
            return View();
        } 

        [HttpPost]
        [Route("{user}/{itemid}")]
        public IActionResult PurchaseItem(string user, int itemid, int amount){
            Console.WriteLine("In PurchaseItem");
            ViewBag.User = context.GetOneUser(HttpContext.Session.GetInt32("UserId"));
            if(ViewBag.User == null){
                return RedirectToAction("Index", "Home", new {area = "Account"});
            }
            ListedItem Item = context.GetOneListedItem(itemid);
            if(Item == null){
                return RedirectToAction("OtherShop", new{ username = user});
            }

            if(context.PurchaseItem(ViewBag.User, Item, amount)){
                TempData["Success"] = "Thank you for your purchase!";
            }
            else{
                TempData["Error"] = "Something went wrong with your purchase...";
            }
            
            return RedirectToAction("OtherShop", new{ username = user});
        }

        [HttpPost]
        [Route("update")]
        public IActionResult UpdateStock(IDictionary<int, ListedItem> UpdateProds){
            ViewBag.User = context.GetOneUser(HttpContext.Session.GetInt32("UserId"));
            if(ViewBag.User == null){
                return RedirectToAction("Index", "Home", new {area = "Account"});
            }
            foreach(KeyValuePair<int, ListedItem> Prod in UpdateProds){
                ListedItem ExistingItem = context.GetOneListedItem(Prod.Key);
                if(ExistingItem == null){
                    TempData["ErrorMessage"] = "Oops! It looks like one of those items doesn't exist anymore... " + 
                                                "maybe it was bought or already removed?";
                    return RedirectToAction("MyShop");
                }
                int AmountDifference = ExistingItem.Stock - Prod.Value.Stock;
                if(AmountDifference > 0){
                    Console.WriteLine("Adding " + AmountDifference + " back to inventory!");
                    InventoryItem AddBack = new InventoryItem();
                    AddBack.ItemId = ExistingItem.ItemId;
                    AddBack.UserId = ViewBag.User.UserId;
                    AddBack.Amount = AmountDifference;
                    context.AddToInventory(AddBack);
                }
                if(ExistingItem.Stock <= 0 || Prod.Value.Stock <= 0){
                    Console.WriteLine("About to delete this Item!");
                    context.Remove(ExistingItem);
                    continue;
                }
                ExistingItem.Price = Prod.Value.Price;
                ExistingItem.Stock = Prod.Value.Stock;
            }
            context.SaveChanges();
            return RedirectToAction("MyShop");
        }

        

        [HttpGet]
        [Route("lose")]
        public IActionResult LoseMoney(){
            User CurUser = context.GetOneUser(HttpContext.Session.GetInt32("UserId"));
            if(CurUser != null){
                CurUser.SubtractMoney(50);
                context.SaveChanges();  
            }
            return RedirectToAction("Index", "Home", new {area = "Account"});
        }

        [HttpGet]
        [Route("add")]
        public IActionResult AddMoney(){
            User CurUser = context.GetOneUser(HttpContext.Session.GetInt32("UserId"));
            if(CurUser != null){
                CurUser.Balance += 25;
                context.SaveChanges();
            }
            return RedirectToAction("Index", "Home", new {area = "Account"});
        }
    }
}

SpiritMarket/Areas/Gameplay/Views/Shops/AllShops.cshtml
@{
    Layout = "_HomeLayout";
    ViewData["Title"] = "Home";
    ViewData["Username"] = @ViewBag.User.Username;
    ViewData["User"] = @ViewBag.User;
}

<h1>All Shops</h1> 
<table class="table table-hover">
    <thead>
        <tr>
        <th scope="col"><h5>Shop Owner</h5></th>
        <th scope="col"><h5>Shop Name</h5></th>
        </tr>
    </thead>
    <tbody>
        @{
            foreach(Shop shop in ViewBag.AllShops){
                <tr>
                    <th scope="row" style="vertical-align: middle;"><h5>@shop.User.Username</h5></th>
                    <td style="vertical-align: middle;"><a asp-action="OtherShop" asp-route-username=@shop.User.Username><h5>@shop.Name</h5></a></td>
                </tr>
            }
        }
    </tbody>
</table>

SpiritMarket/Areas/Gameplay/Views/Shops/CreateMyShop.cshtml
@{
    Layout = "_HomeLayout";
    ViewData["Title"] = "Home";
    ViewData["Username"] = @ViewBag.User.Username;
    ViewData["User"] = @ViewBag.User;
}

<div class="card border-success mb-3 mt-3 ml-auto mr-auto" style="max-width: 75%;">
    <div class="card-header border-success text-center">
        <b>Create a shop!</b>
    </div>
    <div class="card-body text-success">
        <h5 class="card-title">Don't have a shop yet?</h5>
            @{
                @if(@ViewBag.NoMoney == null || @ViewBag.NoMoney.Length == 0)
                {
                    <text>
                    <p class="card-text">Spirit Shops are easy to set up! For a small fee of 75 Spirit Gems, you too can have your own shop!
                        Simply tell us what you want the name of your shop to be!
                    </p>
                    </text>
                }
                else
                {
                    <p class="card-text text-danger">
                        @ViewBag.NoMoney
                    </p>
                }
            }
            
        @model Shop
        <form asp-action = "CreateShop" asp-controller="Shops" method="post">
            <div class = "form-group row">
                <label asp-for="Name" class="col-sm-4 col-form-label text-center text-muted"></label>
                <div class="col-sm-8">
                    <input asp-for="Name" class="form-control" placeholder="Shop Name (32 characters max)">
                    <small class="form-text text-danger"><span asp-validation-for="Name"></span></small>
                </div>
            </div>
            <hr>
            <button type="submit" class="btn btn-success float-right">Create Shop!</button>
        </form>
    </div>
</div>

SpiritMarket/Areas/Gameplay/Views/Shops/MyShop.cshtml
@{
    Layout = "_HomeLayout";
    ViewData["Title"] = "Home";
    ViewData["Username"] = @ViewBag.User.Username;
    ViewData["User"] = @ViewBag.User;
}

<h1>@ViewBag.MyShop.Name</h1>
<h5 class="text-danger">@ViewBag.ErrorMessage</h5>
@model IDictionary<int, ListedItem>
<form action="update" method="POST">
    <table class="table table-hover">
        <thead>
            <tr>
            <th scope="col" class="text-center" ><h5>Item</h5></th>
            <th scope="col" class="text-center" ><h5>Amount (Current)</h5></th>
            <th scope="col" class="text-center" ><h5>Price Per Item (Current)</h5></th>
            </tr>
        </thead>
        <tbody>
            @{
                @for(var i = 0; i < ViewBag.MyShop.Items.Count; i++){
                <tr>
                    <input type="hidden" name="@("UpdateProds[" + @i + "].Key")" value=@ViewBag.MyShop.Items[i].ListedItemId>
                    <th class="text-center" scope="row" style="vertical-align: middle;">
                        <img src="~/images/@ViewBag.MyShop.Items[i].Item.Image" class="inventory">
                        <h5>@ViewBag.MyShop.Items[i].Item.Name</h5>
                    </th>
                    <td class="text-center" style="vertical-align: middle;"><h5>
                        <input name="@("UpdateProds[" + @i + "].Value.Stock")" type="number" step="1" 
                        min="0" max=@ViewBag.MyShop.Items[i].Stock required value=@ViewBag.MyShop.Items[i].Stock>
                        (Currently: @ViewBag.MyShop.Items[i].Stock)</h5>
                    </td>
                    <td class="text-center" style="vertical-align: middle;"><h5>
                        <input name="@("UpdateProds[" + @i + "].Value.Price")" type="number" step="1" 
                        min="0" max="999999" required value=@ViewBag.MyShop.Items[i].Price>
                        (Currently: @ViewBag.MyShop.Items[i].Price)</h5>
                    </td>
                </tr>
                }
            }
        </tbody>
    </table>
    <div class="float-right">
        <button type="submit" class="btn btn-success">Update Shop!</button>
    </div>
</form>

SpiritMarket/Areas/Gameplay/Views/Shops/OtherShop.cshtml
@{
    var titlesuffix = "'s shop";

    Layout = "_HomeLayout";
    ViewData["Title"] = @ViewBag.OtherUser.Username + @titlesuffix;
    ViewData["Username"] = @ViewBag.User.Username;
    ViewData["User"] = @ViewBag.User;
}

<h1>@ViewBag.Shop.Name</h1>
<h5>Owned by @ViewBag.OtherUser.Username</h5>
<h5 class="text-success">@ViewBag.Success</h5>
<h5 class="text-danger">@ViewBag.Error</h5>
@{
    foreach(ListedItem item in @ViewBag.Shop.Items)
    {
        if(item.Price > 0){
            var buyid = "buyform" + @item.ListedItemId;
            var popupid = "popup" + @item.ListedItemId;
            <text>
                <div id="@buyid" class="d-none">
                    <button onclick="testfunction()" class="btn btn-success buyitem">Buy</button>
                </div>
                <a tabindex="@item.ListedItemId" data-container="body" id = "@popupid" 
                data-toggle="popover" title="@item.Item.Name x @item.Stock <br> @item.Price SG"
                data-itemname="@item.Item.Name" data-itemamount="@item.Stock" data-username="@ViewBag.OtherUser.Username"
                data-stockid="@item.ListedItemId" data-unitprice="@item.Price">
                    <img class="inventory m-0" src="~/images/@item.Item.Image" style="border: 0;">
                </a>
            </text>
        }
    }
}

@section Scripts{
    <script>
    $(function(){
        var balance = parseFloat(@ViewBag.User.Balance);
        $('[data-toggle="popover"]').popover({
            html: true,
            trigger: 'click',
            placement: 'right',
            content: function(){
            return '<form class="parentform" action="' + $(this).data("username") + '/' + $(this).data("stockid") + '" method="post">' +
                        '<div class="form-group row">' + 
                            '<label for="amount" class="col-sm-6 col-form-label"><h5>Amount</h5></label>' + 
                            '<div class="col-sm-6">' + 
                                '<input class="form-control dynamicamount" data-unitprice="' + $(this).data("unitprice") + '" data-stockid="' + 
                                $(this).data("stockid") + '" id="amount" type="number" step="1" name="amount" min="1" max="' + 
                                $(this).data("itemamount") + '" required value="1">' + 
                            '</div>' +
                        '</div>' + 
                        '<div class="row">' + 
                            '<h5 class="col-sm-6">Price</h5>' + 
                            '<h5 class="col-sm-6 dynamicprice" id="price' + 
                            $(this).data("stockid") + '">' + $(this).data("unitprice") + ' SG</h5>' + 
                        '</div>' + 
                        '<button type="submit" class="btn btn-success" id="buy' + $(this).data("stockid") + '">Buy</button>' + 
                    '</form>';
            }
        });

        $("body").on("click", ".inventory", function(){
            $(".dynamicamount").on("input", function(){ 

                var unitprice = parseFloat($(this).data("unitprice"));
                var amount = parseInt($(this).val());
                var totalprice = unitprice * amount;
                var textcolor = totalprice > balance ? "red" : "black";
                $("#price" + $(this).data("stockid")).html(totalprice + " SG");
                $("#price" + $(this).data("stockid")).css({"color": textcolor});
                if(textcolor == "red"){
                     $("#buy" + $(this).data("stockid")).attr("disabled", true);
                }
                else{
                    $("#buy" + $(this).data("stockid")).attr("disabled", false);
                }
            });
        });
    });
    </script>
}